# Generated by Django 5.2.4 on 2025-08-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_alter_consumedfood_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumedfood',
            name='nutrition',
        ),
        migrations.AddField(
            model_name='consumedfood',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='consumedfood',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='consumedfood',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='consumedfood',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
