# Generated by Django 5.2.4 on 2025-08-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='diet_type',
            field=models.CharField(choices=[('none', 'None'), ('keto', 'Keto'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('paleo', 'Paleo'), ('regular', 'Regular')], default='none', max_length=20),
        ),
    ]
